### ISSUE TITLE
Why user management feature is not available in Fabric8?

### ISSUE THREAD

**Issue by tapas4java** [fabric8io/fabric8-platform#102]
Hi, 

I am playing with Fabric8 since couple of months now and I really stared liking it. Just wanted to clarify one thing, how it will work in enterprise environment without having user management in place?? Is there any particular reasoning behind for not having user management feature in Fabric8??

**Comment by jstrachan** [comment]
our plan is to use [Keycloak](http://www.keycloak.org/) as the SSO engine for user management which will then allow integration with things like github or google authentication; or customers LDAP or whatever

**Comment by tapas4java** [comment]
Thanks @jstrachan , Any work has been started on this or its still in planning phase?

**Comment by jstrachan** [comment]
@tapas4java yeah, we have a keycloak app:
https://github.com/fabric8io/fabric8-devops/tree/master/keycloak

and we're working on a keycloak operator that will auto-register apps with keycloak on startup:
https://github.com/jimmidyson/keycloak-operator

once thats working we're hoping to move across the console, jenkins + gitlab over to use SSO via keycloak

**Comment by tapas4java** [comment]
@jstrachan Sounds great! Thanks for sharing the info.

**Comment by jimmidyson** [comment]
There's a bit of work to get some changes in to community Keycloak image (https://github.com/jboss-dockerfiles/keycloak/pull/63) before we can support it on both Kubernetes & OpenShift.
