### ISSUE TITLE
user 'developer' not approved error

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-platform#1029]
The token claims ( in the token issued by keycloak ) didn't have the `approved` attribute which was making the auth code feel that user is not approved. 

So in the above screen, I 'told keycloak' to pass the `approved` attribute in the token claims too . After that things worked again. I noticed that this 'mapper' which I've shown in the above screenshot is already there in the prod keycloak.

**Comment by sbose78** [comment]
@jstrachan @rawlingsj I'd like to assign this to myself - reproduce and validate/fix.
Could you add me to the org?

**Comment by rawlingsj** [comment]
> I'd like to assign this to myself - reproduce and validate/fix.
Could you add me to the org?

@sbose78 sure - invite sent

**Comment by sbose78** [comment]
fixed in https://github.com/fabric8-apps/keycloak-app/commit/a146cad60de8b9cd9ac2aa6643d42c48ec18a6b9
