### ISSUE TITLE
Can't Deploy Platform - CD Pipeline Install Failing

### ISSUE THREAD

**Issue by faithword** [fabric8io/fabric8-platform#105]
I can't seem to be able to deploy the latest release of the fabric8 platform due to the installation of the cd-pipeline package failing. It seems to me like it is a configuration issue within the yml file.
Please see console errors below. Thanks.

Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value platform.....✘ 
Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value platform.....✘ 
Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value platform.....✘ 
Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value

**Comment by rawlingsj** [comment]
What version of kubernetes are you running. My guess at the moment is that we need to update the init container spec to include a pull policy when running on kubernetes 1.5.x. Most of the core team are on holiday at the moment. If you're able to try against kubernetes 1.4.x then thet should be ok. If not we'll be sure to address any 1.5 compatibility issues asap next week.

**Comment by faithword** [comment]
@rawlingsj Thanks for pointing me in the right direction. The install uses version 1.5.1 of kubernetes by default. I switched to version 1.4.5 and everything now works fine.
I think this should be added to the documentation so others don't waste so much time on this as much as I have done.
Thanks.
