### ISSUE TITLE
installation instructions assume keycloak installed?

### ISSUE THREAD

**Issue by petenorth** [fabric8io/fabric8-platform#307]
I have tried to follow the installation instructions but they seem to assume that the keycloak pods/services/routes are installed already on minishift i.e.

echo https://$(oc get route keycloak -o jsonpath="{.spec.host}")/auth/realms/fabric8/broker/github/endpoint
 
returns an error because the route 'keycloak' does not exist? Where is keycloak getting deployed to Openshift? I assume it gets installed via the 'install.sh' but if this is the case then the shell script above should be run after the install and gitlab be updated accordingly i.e. interact with gitlab at the beginning and end of the installation process?

Peter.

**Comment by rawlingsj** [comment]
Ah good point - I think we moved this around slightly.  I think we can instead use..
```
echo  https://keycloak-fabric8.$(minishift ip).nip.io/auth/realms/fabric8/broker/github/endpoint
```

I'll fix the docs now, thanks!

**Comment by rawlingsj** [comment]
docs updated

**Comment by rawlingsj** [comment]
https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md#setup-github-client-id-and-secret
