### ISSUE TITLE
Error with GitHub logon

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8-platform#415]
HI,

Trying James' instructions (https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md) and getting this after reaching the Fabric8 logon page when I select GitHub:

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"gtItBFKsP3VO6Va2JG4mvGFYkVZlQ5dlz34whDGQaiM.fabric8-online-platform"}

If I then retry the original fabric8 URL I see the main page and I appear to be logged on. When I then try to create a Space and end up with an error & success indication?

**Comment by stevef1uk** [comment]
Seems to be the same issue as: https://github.com/fabric8io/fabric8-platform/issues/295

**Comment by rawlingsj** [comment]
Late last week we reverted back to using http when running minishift / minikube so we can avoid accepting all the self signed certs initially.  FWIW non local deployments are expected to still use https.

Would you mind having another go now that our docs and release are aligned to only use http please?

**Comment by stevef1uk** [comment]
James, sorry for the delay in getting back to you. I've ben on holiday and only recently got good broadband.

Yes, I can confirm this now works using the minishift 1.3.0 release
