### ISSUE TITLE
install-openshift.sh oauth issue

### ISSUE THREAD

**Issue by DarrenRatcliffe** [fabric8io/fabric8-platform#425]
If I use the install-openshift.sh script with an 'allinone' openshift installation created by oc cluster up it results in oauth not working. If you load the fabric8 console and use the openshift v3 button it generates oauth errors

**Comment by rawlingsj** [comment]
When did you try the install?  Can you check what the output of `oc get oauthclients fabric8-online-platform` you might want to omit your domain in the redirect URL.

Is this on minishift or a remote openshift cluster?

**Comment by DarrenRatcliffe** [comment]
@rawlingsj I tried it a few times over the weekend, I will try a further deployment to test and post output

I am installing openshift in to a CentOS 7 vm using oc cluster up, so single node, all in one.

**Comment by DarrenRatcliffe** [comment]
@rawlingsj the output is as follows:
`NAME                      SECRET    WWW-CHALLENGE   REDIRECT URIS
fabric8-online-platform   fabric8   FALSE           http://keycloak-myproject.xx.xx.xx.xx.nip.io/auth/realms/fabric8/broker/openshift-v3/endpoint`

**Comment by rawlingsj** [comment]
And can you add the oauth error you're getting please?

**Comment by rawlingsj** [comment]
We released new version this morning that switches from a default routes of https to http.  The install script however already had the change last friday so I suspect we have a timing issue of the script being updated and the release being available.

Could you try the install script again please, if it's easy to trash your VM that might be best to avoid old resources hanging around (just in case).

FWIW the move to http is only to improve UX and avoid accepting lots of self signed certs when running locally.  Proper installations would have signed https certificates for the routes.  The automatic creation of these certs in something that will come in the future.

**Comment by rawlingsj** [comment]
You will also want to check the github oathclient you created uses http in the redirect URL and not https.  The docs changed last friday so again it depends on when you created the github oauth client https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md#setup-github-client-id-and-secret

**Comment by DarrenRatcliffe** [comment]
@rawlingsj wrt your last point, when we use http keycloak throws any error saying it requires https?
![image](https://user-images.githubusercontent.com/1911051/28030176-908f90fc-659a-11e7-904f-b57be6964203.png)

**Comment by DarrenRatcliffe** [comment]
Can I just check what the recommended versions are for running the fabric8-platform on:
openshift origin: v?
docker: v?

**Comment by DarrenRatcliffe** [comment]
Also the install-openshift.sh doesn't handle the creating the developer & fabric8 projects then switching to system:admin for adding the OAuthClient and cluster-admin role to the init-tenant service account then switching back to the developer user which it does in the minishift install.sh

**Comment by DarrenRatcliffe** [comment]
one other observation is that the init-tenant deployment is not completing with a pod error stating that "Couldn t find key kubernetes mode in config map fabric 8 f 8 tenant"

**Comment by rawlingsj** [comment]
I've updated the `install-openshift.sh`script and tested it using `oc cluster up` and all the pods start but there's a CORS issue in the UI.  I'm not sure if there's an easy way to enable CORS with oc cluster up yet but in the short term this might be a workaround https://github.com/fabric8io/gofabric8/issues/98#issuecomment-243406247
