### ISSUE TITLE
Import existing code did not works

### ISSUE THREAD

**Issue by aboucham** [fabric8io/fabric8-platform#530]
With the latest version, we can't import existing code in Forge Wizard, we receive the following error:

"Repository Name must be specified. The regex pattern to match repositories name."

![forge_wizard](https://user-images.githubusercontent.com/29703868/28410987-480ff908-6d37-11e7-8857-b4d278fe8cec.png)

**Comment by jstrachan** [comment]
I wonder if you could try again with the latest distro? I saw that too recently but I think it's now fixed

**Comment by aboucham** [comment]
I just tried the latest distro, and i confirm the pb is resolved, Thanks James :+1:
