### ISSUE TITLE
create a keycloak theme without the 'github' button 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-platform#539]
when running on minishift, if the user logs in first with 'github' then the username in KC is set to the github user name. 

However when logging first via openshift, it uses the openshift `whoami` name (e.g. `developer`).

Though the fabric8-tenant always uses the openshift name - so `developer` - however the fabric8-ui uses the KC user name (so the github user id) as the name of the namespaces to look for. 

So until we figure out a way to get login via github working (versus openshift) we should remove the github button on the KeyCloak theme. Once its working again we can add it back again!

**Comment by alexeykazakov** [comment]
You could set opensfhit as the default IdP in Keycloak so it's always used by default.

**Comment by jstrachan** [comment]
Ah thanks! So if openshift is the default IdP then clicking on the 'github' button to login on the keycloak theme would still use the openshift user ID? I'll give it a try - thanks!

**Comment by alexeykazakov** [comment]
No, but if openshift is used by default then KC should redirect to openshift and you won't see the KC login page at all.
You can still login via github by using kc_idp_hint="github" parameter if needed.

**Comment by sbose78** [comment]
@jstrachan ,

As a comparison: In our saas, we have RHD set as default IDP, that's why we don't see a Keycloak login page at all - it takes the user to RHD login directly.

So for the upstream project, you could set 'openshift' as the default IDP, and so:
1. User won't see the KC login page at all and will be going on to login via OpenShift.
2. Post login, user will land up on the `Getting started` page to connect Github.

**Comment by jstrachan** [comment]
thanks for the heads up @sbose78 @alexeykazakov 

one question though; on the SaaS if RHD is the default IDP; how come the UI uses the OSO username rather than the RHD user name? Or to put that another way - is there gonna be an issue on the SaaS if the OSO username is different from the RHD user name?

**Comment by alexeykazakov** [comment]
openshift.io UI uses RHD usernames actually. OSO just happened to use RHD usernames too. Maybe because OSO is using RHD as the default IdP too :)
And yes there gonna be an issue if OSO and RHD usernames don't match.

**Comment by jstrachan** [comment]
@alexeykazakov aha of course! Many thanks for all of that - I'm now grokking the issues we've been having on  minishift much better now thanks!

**Comment by rawlingsj** [comment]
fixed via https://github.com/fabric8io/fabric8-platform/pull/610, on minikube it now looks like this..

<img width="1440" alt="screenshot 2017-07-31 16 07 02" src="https://user-images.githubusercontent.com/1457180/28784740-34bc1692-760c-11e7-9ff7-388692589937.png">

**Comment by rawlingsj** [comment]
FWIW the theme is mounted into the keycloak pod using a gitRepo volume https://github.com/fabric8io/fabric8-keycloak-theme

This also makes its easy for folks to clone and customise.
