### ISSUE TITLE
Unable to login in to fabric8 console

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-platform#729]
After setting up the github oAuth2 app, the fabric8-platform deployed on minishift is unable to login the default user `developer/developer` 

The keycloak logs in shows some trustAnchor errors https://gist.github.com/kameshsampath/23bcfa5f9a680371c220ec3d9da08e09 

Upon doing some analysis in `fabric8/keycloak-postgress` pod, its observed that the startup takes argments "-Djavax.net.ssl.trustStore=/opt/jboss/keycloak/standalone/configuration/tls/openshift-truststore.jks" (https://github.com/kameshsampath/fabric8-platform/blob/master/apps/keycloak/src/main/fabric8/deploymentConfig.yml#L147) unfortunately the file `/opt/jboss/keycloak/standalone/configuration/tls/openshift-truststore.jks` is owned by root with `rw` only on root. This might be causing the trustAnchor issues as the application will not be able to read the `jks` .

**Comment by kameshsampath** [comment]
@jstrachan / @rawlingsj   I am not able to find where the fabric8/keycloak-postgres image sources lives to do a quick check to fix the permissions and see.

**Comment by jstrachan** [comment]
Was this on minishift 1.4.1?

The app is here
https://github.com/fabric8-services/keycloak-deployment

**Comment by kameshsampath** [comment]
yes @jstrachan on minishift 1.4.1 with OSO v3.6

**Comment by kameshsampath** [comment]
@jstrachan ideally the issue seem to be here https://github.com/kameshsampath/fabric8-platform/blob/master/apps/keycloak/src/main/fabric8/deploymentConfig.yml#L29-L43 since the image of @jimmidyson  will be run root, the permissions on the file will naturally inherit. If we can add chown to JBoss user then we should be able to get past this issue

**Comment by jstrachan** [comment]
@kameshsampath great catch! I wonder why its working for us though ;) - you on OS X? Wonder if its VM related; I've been using xhyve - which VM were you using? 

@rawlingsj does minishift work for you right now (am knee deep testing a new fabric8-platform PR for a little while)

**Comment by rawlingsj** [comment]
Sure thing, I just tested it here and it worked as expected:
```
minishift start --vm-driver=xhyve --memory=6096 --cpus=5
gofabric8 deploy --namespace fabric8 -y --package=system
```
One thing is the console opened up before the keycloak init container had completed and pod started so the login would fail.  The next release includes the dependency init container so the browser wont open until ready to be used.  

I think I have seen this issue before though; when I updated to a newer version of minishift.  My quick fix at the time was to `minishift delete && rm -rf ~/.minishift` to make sure everything was clean.  Then ran the create steps again.

**Comment by rawlingsj** [comment]
Oh and I was able to log in too..

<img width="1377" alt="screenshot 2017-08-17 09 36 05" src="https://user-images.githubusercontent.com/1457180/29403219-9dafdad2-832f-11e7-9209-de20aac8f579.png">

**Comment by kameshsampath** [comment]
@jstrachan - am using xhye on OS X as well. 

@rawlingsj - let me clean and try it once as well

**Comment by kameshsampath** [comment]
@rawlingsj  - clear does help in this case. But my point on the truststore holds good might come in to play when we use https:// for the endpoints.

**Comment by rawlingsj** [comment]
Ok great! Let's close this issue and open a new specific one once we check openshift + https?
