### ISSUE TITLE
lets default to use internal URLs to access git (gogs / gitlab repos) where possible in forge + jenkins

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-platform#81]
its super common for folks to have DNS, firewall or ip6 issues where they cannot access the external URL for gogs repos from inside `fabric8-forge` or `jenkins`

So lets default instead to using internal kubernetes URLs (e.g. `http://gogs/...`) instead as that always works for everyone.

We can configure this in the fabric8-forge ConfigMap if folks want to opt out of the use of internal URLs

**Comment by haikuo81** [comment]
Hi @jstrachan , this commit encounter issue when I import project from external git like github,gitlab,  the git url will be configured start with http://gogs/..., we expect it as https://github.com/.....,


Jenkins pipeline error: import from external GIT resets URL to http://gogs
#6835
